name: Watch and Notify 25分
#on:
#  pull_request:
#    branch:
#      - master
#  push:
#    branch:
#      - master
on:
  schedule:
    - cron: "25 0-10 * * 1-5"
    # 平日 9~19時間 5分単位
    # - cron: "*/5 0-10 * * 1-5"
    # 10분에 한번씩 실행
    #- cron: "*/10 * * * *"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          make install
          #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute Python script # Run the run.py to get the latest data
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          make run
